### ISSUE TITLE
ubuntu compilation dumbness

### ISSUE THREAD

**Issue by spikeysnack** [themanyone/tape#1]
Problems with building -- 
A:
ubuntu packages are "lzma , lzma-dev"  
( "xz-lzma" package also exists but "contains no files" and adds no files and refuses to install ...??? (bogus!))

B:
needed to prefix CFLAGS 
CFLAGS="-std=c99"  ./configure --with-gnu-ld --with-xz --enable-dependency-tracking

C:
Kept getting libtool error   "cannot file libtape  | tape.o " 
It turns out there I kept your stuff in /usr/local/src/Henry Kroll/ 
and libtool hates spaces in dir names or something.
So I copied it to /usr/local/src/tape  , tried again.
more weird cryptic library path errors.

Nothing worked until I changed the line in src/Makefile.am or src/Makefile.in
from 
tape_LDFLAGS = -lm -ltape 
to
tape_LDFLAGS = -ltape -lm
then libtool was cool. (dumb!)

**Comment by themanyone** [comment]
Hmm, that's interesting.  -std=c99 is in Makefile.am, but maybe it's only picking it up for tape.

* Changed tape_CFLAGS to AM_CFLAGS and it builds
* Was not aware of enable-dependency-tracking flag. It's rice. Already enabled. Unnecessary.
* --with-xz should be the default. It works without it.
* Use --with-xz=[anything other than yes] to disable xz.
* Changed the order of _LDFLAGS to -tape -lm
* --with-gnu-xx is supposedly only necessary on hppa* / sparc

Old Automake version maybe? It should work out of box now, mmhmm.
Thanks for testing!
